### ISSUE TITLE
Document build dependencies

### ISSUE THREAD

**Issue by englishm** [exupero/v#1]
`make` failed when calling out to `sjs`.
Googling for `sjs` led me to http://onilabs.com/stratifiedjs.

It turns out that this is not the right `sjs`.
I think that I need to get https://github.com/sinelaw/infernu installed instead.

**Comment by exupero** [comment]
Actually, `sjs` is the executable for [sweet.js](http://sweetjs.org/).

I've added it to the package.json, updated the Makefile to use `node_modules/.bin/sjs` rather than an executable in a `PATH` directory, and added to the Readme that one needs to run `npm install` in order to build.

**Comment by englishm** [comment]
:+1: 
Thanks!
